routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin/login');
});

Route::get('/home', function () {
    return redirect('/admin/login');
});


/*
|--------------------------------------------------------------------------
| @PRX Admin Routes
|--------------------------------------------------------------------------
*/
Route::name('admin.')
    ->prefix('admin')
    ->middleware('prxadmin')
    ->group(function() { 


		/*
		|--------------------------------------------------------------------------
		| @Room
		|--------------------------------------------------------------------------
		*/
		Route::resource('rooms', 'RoomController')->except([
			'create',
			'show'
		]);
		Route::get('rooms/create/{project?}/{name?}', 'RoomController@create')->name('rooms.create');

		/*
		|--------------------------------------------------------------------------
		| @Amenities
		|--------------------------------------------------------------------------
		*/
		Route::resource('amenities', 'AmenityController')->except([
			'create',
			'show'
		]);
		Route::get('amenities/create/{project?}/{name?}', 'AmenityController@create')->name('amenities.create');	


		/*
		|--------------------------------------------------------------------------
		| @Commercial Areas
		|--------------------------------------------------------------------------
		*/
		Route::resource('commercial-areas', 'CommercialAreaController')->except([
			'create',
			'show'
		]);
		Route::get('commercial-areas/create/{project?}/{name?}', 'CommercialAreaController@create')->name('commercial-areas.create');	


		/*
		|--------------------------------------------------------------------------
		| @Sold Out Project
		|--------------------------------------------------------------------------
		*/
		Route::resource('sold-out-projects', 'SoldOutProjectController')->except([
			'show'
		]);
		Route::get('sold-out-projects/{project}/{name}', 'SoldOutProjectController@show')->name('sold-out-projects.show');		

		/*
		|--------------------------------------------------------------------------
		| @Room Layout
		|--------------------------------------------------------------------------
		*/
		// Route::resource('room-layout', 'RoomLayoutController')->except([
		// 	'create',
		// 	'show'
		// ]);
		// Route::get('room-layout/create/{floor_layout?}/{name?}', 'RoomLayoutController@create')->name('room-layout.create');

		/*
		|--------------------------------------------------------------------------
		| @Home page banner
		|--------------------------------------------------------------------------
		*/
		Route::resource('home-banner', 'HomeBannerController')->except([
			'show',
			'destroy'
		]);

		/*
		|--------------------------------------------------------------------------
		| @General Page
		|--------------------------------------------------------------------------
		*/
		Route::resource('general-pages', 'GeneralPageController')->except([
			'create',
			'store',
			'show',
			'destroy'
		]);
		Route::get('general-pages/{page}/{name}', 'GeneralPageController@show')->name('general-pages.show');

		/*
		|--------------------------------------------------------------------------
		| @General Page item
		|--------------------------------------------------------------------------
		*/
		Route::resource('general-page-item', 'GeneralPageItemController')->except([
			'create',
			'store',
			'show',
			'destroy'
		]);

		Route::resource('exchange_rates', 'ExchangeRateController');

		Route::resource('room_types', 'RoomTypeController');


		Route::group(['prefix' => 'projects'], function() {

			/*
			|--------------------------------------------------------------------------
			| @Project
			|--------------------------------------------------------------------------
			*/
			Route::get('/', 'ProjectController@index')->name('project.index');
			Route::get('{project}/{name}', 'ProjectController@show')->name('project.view');
			Route::get('edit/{project}/{name}', 'ProjectController@edit')->name('project.edit');
			Route::put('update/{project}', 'ProjectController@update')->name('project.update');

			Route::get('building-layout/{project}/{name}', 'BuildingLayoutController@index')->name('building-layouts.index');
			Route::get('/building-layout/store/{project}/{name}', 'BuildingLayoutController@create')->name('project.layout.create');
			Route::post('/building-layouts/store/{project}', 'BuildingLayoutController@store')->name('building-layout.store');
			Route::get('building-layout/{project}/{layout}/edit', 'BuildingLayoutController@edit')->name('building-layout.edit');
			Route::put('building-layout/{layout}/update', 'BuildingLayoutController@update')->name('building-layout.update');	
			Route::delete('building-layout/{layout}/destroy', 'BuildingLayoutController@destroy')->name('building-layout.destroy');		



			/*
			|--------------------------------------------------------------------------
			| @Gallery
			|--------------------------------------------------------------------------
			*/	
			Route::get('gallery/{project}/{name}', 'GalleryController@index')->name('gallery.index');
			Route::get('gallery/create/{project}/{name}', 'GalleryController@create')->name('gallery.create');
			Route::get('gallery/edit/{id}/{project}/{name}', 'GalleryController@edit')->name('gallery.edit');
			Route::post('gallery/store/{project}', 'GalleryController@store')->name('gallery.store');
			Route::put('gallery/update/{id}', 'GalleryController@update')->name('gallery.update');
			Route::delete('gallery/destroy/{id}', 'GalleryController@destroy')->name('gallery.destroy');

			/*
			|--------------------------------------------------------------------------
			| @Floor Layout
			|--------------------------------------------------------------------------
			*/
			Route::get('{project}/{name}/floor-layouts/', 'FloorLayoutController@index')->name('floor-layout.index');
			Route::get('{project}/{name}/floor-layoust/create', 'FloorLayoutController@create')->name('floor-layout.create');
			Route::post('{project}/floor-layouts/store', 'FloorLayoutController@store')->name('floor-layout.store');
			Route::get('/{project?}/{floor}/floor-layouts/edit', 'FloorLayoutController@edit')->name('floor-layout.edit');

			Route::put('{project?}/{floor}/floor-layouts/update', 'FloorLayoutController@update')->name('floor-layout.update');

			Route::delete('floor-layouts/{floor}/destroy', 'FloorLayoutController@destroy')->name('floor-layout.destroy');


			/*
			|--------------------------------------------------------------------------
			| @Floor Layout
			|--------------------------------------------------------------------------
			*/
			Route::get('units/{floor}/{name}', 'UnitController@index')->name('units.index');
			Route::get('units/{floor}/{name}/create', 'UnitController@create')->name('units.create');
			Route::post('units/{floor}/store', 'UnitController@store')->name('units.store');
			Route::get('units/{floor}/{unit}/edit', 'UnitController@edit')->name('units.edit');
			Route::put('units/{unit}/update', 'UnitController@update')->name('units.update');	
			Route::delete('units/{unit}/destroy', 'UnitController@destroy')->name('units.destroy');	

			/*
			|--------------------------------------------------------------------------
			| @Room Layout
			|--------------------------------------------------------------------------
			*/
			// Route::get('room-layouts/{floor}/{name}', 'RoomLayoutController@index')->name('room-layouts.index');	
			// Route::get('room-layouts/{floor}/{name}/create', 'RoomLayoutController@create')->name('room-layouts.create');	
			// Route::post('room-layouts/store', 'RoomLayoutController@store')->name('room-layouts.store');	
			// Route::get('room-layouts/{id}/{unit}/edit', 'RoomLayoutController@edit')->name('room-layouts.edit');	
			// Route::put('room-layouts/{roomlayout}/update', 'RoomLayoutController@update')->name('room-layouts.update');
			// Route::delete('room-layouts/{roomlayout}/destroy', 'RoomLayoutController@destroy')->name('room-layouts.destroy');			
		});

});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Amenity;
use App\CommercialArea;
use App\Room;
use App\Gallery;

class Project extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = [
		'name', 'description', 'address',
        'image_path','longitude', 'latitude', 
        'footer', 'front_outside_image', 'back_outside_image',
        'landmark'
	];

    /*
    |-----------------------------------------------
    | @Relationships
    |-----------------------------------------------
    */

    public function rooms() 
    {
    	return $this->hasMany(Room::class);
    }

    public function amenities() 
    {
        return $this->hasMany(Amenity::class);
    }
    
    public function commercial_areas() 
    {
        return $this->hasMany(CommercialArea::class);
    }

    public function gallery_images() 
    {
        return $this->hasMany(Gallery::class);
    }

    public function building_layouts()
    {
        return $this->hasMany(BuildingLayout::class);
    }

    public function renderImagePath()
    {
        if($this->image_path) {
            return '/storage/' . $this->image_path;
        }
    }

    public function renderOutsideFrontView()
    {
        if($this->front_outside_image) {
            return '/storage/' . $this->front_outside_image;
        }
    }

    public function renderOutsideBackView()
    {
        if($this->back_outside_image) {
            return '/storage/' . $this->back_outside_image;
        }
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ProjectStorePost;

use App\Project;
use Image;

class ProjectController extends Controller
{
    public static $guardResource = 'project';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $projects = Project::get();

        return view('pages.admin.projects.index', [
            'projects' => $projects
        ]);

    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project, $name)
    {
        return view('pages.admin.projects.show', [
            'project' => $project
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project, $name)
    {
        return view('pages.admin.projects.edit', [
            'project' => $project
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectStorePost $request, Project $project)
    {

        $vars = $request->except(['image_path', 'front_outside_image', 'back_outside_image']);

        /** Begin transaction */
        \DB::beginTransaction();

            if($request->hasFile('image_path')) {
                $vars['image_path'] = $request->file('image_path')->store('projects', 'public');
            }

            if($request->hasFile('front_outside_image')) {
                $vars['front_outside_image'] = $request->file('front_outside_image')->store('outside-view', 'public');
            }

            if($request->hasFile('back_outside_image')) {
                $vars['back_outside_image'] = $request->file('back_outside_image')->store('outside-view', 'public');
            }

            /** Update Project */
            $project->update($vars);


        /** Commit transaction */
        \DB::commit();

        /** Flash message */
        \PRXAdmin::view()->flash($project->name. ' has been successfully updated!', 'Success!', 'success');

        return back();

    }
}

app/Http/Controllers/UnitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UnitStorePost;

use App\FloorLayout;
use App\Unit;
use App\RoomType;

class UnitController extends Controller
{
    public static $guardResource = 'units';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(FloorLayout $floor, $name)
    {
        return view('pages.admin.projects.units.index', [
            'floor' => $floor
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(FloorLayout $floor, $name)
    {
        $types = Unit::getTypes();

        return view('pages.admin.projects.units.create', [
            'floor' => $floor,
            'room_types' => RoomType::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UnitStorePost $request, FloorLayout $floor)
    {
        $vars = $request->except(['image_path']);
        $vars['floor_layout_id'] = $floor->id;
        
        if($request->hasFile('image_path')) {

            $vars['image_path'] = $request->file('image_path')->store('room-layouts', 'public');

        }


        /** Start Transaction */
        \DB::beginTransaction();
            /** Create unit */
            $unit = Unit::create($vars);


        /** End Transaction */
        \DB::commit();

        /** Flash message */
        \PRXAdmin::view()->flash($unit->name .' has been successfully created!', 'Success!', 'success');        

        /** Return to unit index */
        return redirect()->route('admin.units.index', [$floor->id, $floor->name]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($floor, Unit $unit)
    {   

        $types = Unit::getTypes();        


// dd($unit->unit_number);
        return view('pages.admin.projects.units.edit', [
            'unit' => $unit,
            'room_types' => RoomType::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UnitStorePost $request, Unit $unit)
    {
        $vars = $request->except(['image_path']);

        if($request->hasFile('image_path')) {

            /** Remove Image from Storage */
            if($unit->image_path) {
                \Storage::delete('public/'. $unit->image_path);
            }

            $vars['image_path'] = $request->file('image_path')->store('room-layouts', 'public');

        }

        /** Start Transaction */
        \DB::beginTransaction();

            /** Create unit */
            $unit->update($vars);

        /** End Transaction */
        \DB::commit();

        /** Flash message */
        \PRXAdmin::view()->flash($unit->name .' has been successfully updated!', 'Success!', 'success');        

        /** Return to unit index */
        return back();

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($unit)
    {
        /** Find Unit */
        $unit = Unit::find($unit);

        /** Begin Transaction */
        \DB::beginTransaction();

            /** Create unit */
            $unit->delete();

        /** End transaction */
        \DB::commit();


        /** Flash message */
        \PRXAdmin::view()->flash('Unit has been successfully removed!', 'Success!', 'success');        

        /** Return to unit index */
        return back();        

    }
}

resources/views/pages/admin/projects/units/create.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Unit
        <small>Add Unit to {{ $floor->name }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-building"></i> Add Unit to {{ $floor->name }}</a></li>
        <li class="active">Create</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-header">
                    <h3 class="box-title">Add Unit to {{ $floor->name }}</h3>
                </div>
                <div class="box-body">
                    
                    @include('PRXAdmin::includes.form-errors')

                    <!-- form start -->
                    <form role="form" method="post" action="{{ route('admin.units.store', $floor->id) }}" enctype="multipart/form-data">

                        {{ csrf_field() }}

                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div id="imageHolder" style="width: 100%; height: 100%; position: relative; text-align: center;">

                                        <!-- Stored units -->
                                        @foreach($floor->units as $unit)
                                            <div style="position: absolute; top: {{ $unit->y_coordinates  }}%; left: {{ $unit->x_coordinates  }}%; color: #fff; font-weight: bold;font-size:18px">{{ $unit->unit_number }}</div>
                                        @endforeach
                                        <img id="image" src="{{ $floor->renderImagePath() }}" width="100%" height="100%">
                                    </div>
                                </div> 

                                <div class="col-md-6">

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Unit/Room Number: </label>
                                            <input type="text" id="unitNumber" name="unit_number" placeholder="Unit Number" class="form-control" value="{{ old('unit_number') }}" required>
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Name: </label>
                                            <input type="text" id="name" name="name" placeholder="Name" class="form-control" value="{{ old('name') }}" required>
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Type: </label>
                                            <select class="form-control" name="room_type_id" id="type">
                                                @foreach($room_types as $type)
                                                    <option value="{{ $type->id }}">{{ $type->name }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea id="description" name="description" rows="3" class="form-control" required>{{ old('description') }}</textarea>
                                        </div> 
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Room <small>(room layout)</small></label>
                                            <input type="file" name="image_path" id="image_path" class="form-control" required>
                                        </div> 
                                    </div>    

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Availability for 360 view</label><br>
                                            <select class="form-control" name="available_360">
                                                <option value="1">Yes, make it available.</option>
                                                <option value="0">No for now.</option>
                                            </select>
                                        </div>
                                    </div>                                

                                    <!-- hidden inputs -->
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <input type="hidden" id="x_coordinates" name="x_coordinates" placeholder="" class="form-control">
                                            <input type="hidden" id="y_coordinates" name="y_coordinates" placeholder="" class="form-control">                                            
                                        </div>
                                    </div>


                                </div>

                            </div>
                        </div>

                        <!-- /.box-body -->
                        <div class="box-footer text-right">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop

resources/views/pages/admin/projects/units/index.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Units
        <small>List of Units of {{ $floor->name }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-building"></i> Units</a></li>
        <li class="active">Index</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row margin-bottom">
        <div class="col-md-12">
            <a href="{{ route('admin.units.create', [$floor->id, $floor->name]) }}" type="button" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Add Unit</a>            
            {{-- <a href="{{ route('admin.room-layouts.index', [$floor->id, $floor->name]) }}" type="button" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Room Layout</a> --}}            
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->      

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Units</h3>
                </div>
                <div class="box-body">
                    <div class="col-md-3"></div>
                        <div class="col-md-6">
                            <div id="imageHolder" style="width: 100%; height: 100%; position: relative; text-align: center;">

                                <!-- Stored units -->
                                @foreach($floor->units as $unit)
                                    <div style="position: absolute; top: {{ $unit->y_coordinates  }}%; left: {{ $unit->x_coordinates  }}%; color: #fff; font-weight: bold;font-size:18px">{{ $unit->unit_number }}</div>
                                @endforeach


                                <img id="image" src="{{ $floor->renderImagePath() }}" width="100%" height="100%">
                            </div>
                        </div>
                    <div class="col-md-3"></div> 
                

                    <div class="row">
                        <div class="form-group">
                            <div class="col-xs-12">
                                <table id="roomTable" class="dataTables table table-bordered">
                                    <thead>
                                        <th>Project</th>
                                        <th>Floor Layout</th>
                                        <th>Name</th>
                                        <th>Room Number</th>
                                        <th>Actions</th>
                                    </thead>

                                    <tbody>
                                        @foreach($floor->units as $unit)
                                            <tr>
                                                <td>{{ $unit->floor->project->name }}</td>
                                                <td>{{ $unit->floor->name }}</td>
                                                <td>{{ $unit->name}}</td>
                                                <td>{{ $unit->unit_number }}</td>
                                                <td>
                                                    <a href="{{ route('admin.units.edit', [$unit->floor->id, $unit->id]) }}" class="btn btn-sm btn-primary">
                                                        <i class="fa fa-edit"></i>
                                                    </a>
                                                    <a class="btn btn-sm btn-danger deleteBtn"
                                                        data-action="{{ route('admin.units.destroy', $unit->id) }}"
                                                        data-message="Are you sure you want to archived {{ $unit->name }} ?">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop