routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin/login');
});

Route::get('/home', function () {
    return redirect('/admin/login');
});


/*
|--------------------------------------------------------------------------
| @PRX Admin Routes
|--------------------------------------------------------------------------
*/
Route::name('admin.')
    ->prefix('admin')
    ->middleware('prxadmin')
    ->group(function() { 


		/*
		|--------------------------------------------------------------------------
		| @Room
		|--------------------------------------------------------------------------
		*/
		Route::resource('rooms', 'RoomController')->except([
			'create',
			'show'
		]);
		Route::get('rooms/create/{project?}/{name?}', 'RoomController@create')->name('rooms.create');

		/*
		|--------------------------------------------------------------------------
		| @Amenities
		|--------------------------------------------------------------------------
		*/
		Route::resource('amenities', 'AmenityController')->except([
			'create',
			'show'
		]);
		Route::get('amenities/create/{project?}/{name?}', 'AmenityController@create')->name('amenities.create');	


		/*
		|--------------------------------------------------------------------------
		| @Commercial Areas
		|--------------------------------------------------------------------------
		*/
		Route::resource('commercial-areas', 'CommercialAreaController')->except([
			'create',
			'show'
		]);
		Route::get('commercial-areas/create/{project?}/{name?}', 'CommercialAreaController@create')->name('commercial-areas.create');	


		/*
		|--------------------------------------------------------------------------
		| @Sold Out Project
		|--------------------------------------------------------------------------
		*/
		Route::resource('sold-out-projects', 'SoldOutProjectController')->except([
			'show'
		]);
		Route::get('sold-out-projects/{project}/{name}', 'SoldOutProjectController@show')->name('sold-out-projects.show');		

		/*
		|--------------------------------------------------------------------------
		| @Room Layout
		|--------------------------------------------------------------------------
		*/
		// Route::resource('room-layout', 'RoomLayoutController')->except([
		// 	'create',
		// 	'show'
		// ]);
		// Route::get('room-layout/create/{floor_layout?}/{name?}', 'RoomLayoutController@create')->name('room-layout.create');

		/*
		|--------------------------------------------------------------------------
		| @Home page banner
		|--------------------------------------------------------------------------
		*/
		Route::resource('home-banner', 'HomeBannerController')->except([
			'show',
			'destroy'
		]);

		/*
		|--------------------------------------------------------------------------
		| @General Page
		|--------------------------------------------------------------------------
		*/
		Route::resource('general-pages', 'GeneralPageController')->except([
			'create',
			'store',
			'show',
			'destroy'
		]);
		Route::get('general-pages/{page}/{name}', 'GeneralPageController@show')->name('general-pages.show');

		/*
		|--------------------------------------------------------------------------
		| @General Page item
		|--------------------------------------------------------------------------
		*/
		Route::resource('general-page-item', 'GeneralPageItemController')->except([
			'create',
			'store',
			'show',
			'destroy'
		]);

		Route::resource('exchange_rates', 'ExchangeRateController');

		Route::resource('room_types', 'RoomTypeController');


		Route::group(['prefix' => 'projects'], function() {

			/*
			|--------------------------------------------------------------------------
			| @Project
			|--------------------------------------------------------------------------
			*/
			Route::get('/', 'ProjectController@index')->name('project.index');
			Route::get('{project}/{name}', 'ProjectController@show')->name('project.view');
			Route::get('edit/{project}/{name}', 'ProjectController@edit')->name('project.edit');
			Route::put('update/{project}', 'ProjectController@update')->name('project.update');

			Route::get('building-layout/{project}/{name}', 'BuildingLayoutController@index')->name('building-layouts.index');
			Route::get('/building-layout/store/{project}/{name}', 'BuildingLayoutController@create')->name('project.layout.create');
			Route::post('/building-layouts/store/{project}', 'BuildingLayoutController@store')->name('building-layout.store');
			Route::get('building-layout/{project}/{layout}/edit', 'BuildingLayoutController@edit')->name('building-layout.edit');
			Route::put('building-layout/{layout}/update', 'BuildingLayoutController@update')->name('building-layout.update');	
			Route::delete('building-layout/{layout}/destroy', 'BuildingLayoutController@destroy')->name('building-layout.destroy');		



			/*
			|--------------------------------------------------------------------------
			| @Gallery
			|--------------------------------------------------------------------------
			*/	
			Route::get('gallery/{project}/{name}', 'GalleryController@index')->name('gallery.index');
			Route::get('gallery/create/{project}/{name}', 'GalleryController@create')->name('gallery.create');
			Route::get('gallery/edit/{id}/{project}/{name}', 'GalleryController@edit')->name('gallery.edit');
			Route::post('gallery/store/{project}', 'GalleryController@store')->name('gallery.store');
			Route::put('gallery/update/{id}', 'GalleryController@update')->name('gallery.update');
			Route::delete('gallery/destroy/{id}', 'GalleryController@destroy')->name('gallery.destroy');

			/*
			|--------------------------------------------------------------------------
			| @Floor Layout
			|--------------------------------------------------------------------------
			*/
			Route::get('{project}/{name}/floor-layouts/', 'FloorLayoutController@index')->name('floor-layout.index');
			Route::get('{project}/{name}/floor-layoust/create', 'FloorLayoutController@create')->name('floor-layout.create');
			Route::post('{project}/floor-layouts/store', 'FloorLayoutController@store')->name('floor-layout.store');
			Route::get('/{project?}/{floor}/floor-layouts/edit', 'FloorLayoutController@edit')->name('floor-layout.edit');

			Route::put('{project?}/{floor}/floor-layouts/update', 'FloorLayoutController@update')->name('floor-layout.update');

			Route::delete('floor-layouts/{floor}/destroy', 'FloorLayoutController@destroy')->name('floor-layout.destroy');


			/*
			|--------------------------------------------------------------------------
			| @Floor Layout
			|--------------------------------------------------------------------------
			*/
			Route::get('units/{floor}/{name}', 'UnitController@index')->name('units.index');
			Route::get('units/{floor}/{name}/create', 'UnitController@create')->name('units.create');
			Route::post('units/{floor}/store', 'UnitController@store')->name('units.store');
			Route::get('units/{floor}/{unit}/edit', 'UnitController@edit')->name('units.edit');
			Route::put('units/{unit}/update', 'UnitController@update')->name('units.update');	
			Route::delete('units/{unit}/destroy', 'UnitController@destroy')->name('units.destroy');	

			/*
			|--------------------------------------------------------------------------
			| @Room Layout
			|--------------------------------------------------------------------------
			*/
			// Route::get('room-layouts/{floor}/{name}', 'RoomLayoutController@index')->name('room-layouts.index');	
			// Route::get('room-layouts/{floor}/{name}/create', 'RoomLayoutController@create')->name('room-layouts.create');	
			// Route::post('room-layouts/store', 'RoomLayoutController@store')->name('room-layouts.store');	
			// Route::get('room-layouts/{id}/{unit}/edit', 'RoomLayoutController@edit')->name('room-layouts.edit');	
			// Route::put('room-layouts/{roomlayout}/update', 'RoomLayoutController@update')->name('room-layouts.update');
			// Route::delete('room-layouts/{roomlayout}/destroy', 'RoomLayoutController@destroy')->name('room-layouts.destroy');			
		});

});

app/Http/Controllers/Api/FloorLayoutController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Project;
use App\FloorLayout;
use App\BuildingLayout;
use App\Unit;
use App\RoomType;

class FloorLayoutController extends Controller
{
    public function index($id)
    {
    	$item = BuildingLayout::find($id);
        $unit_arr = [];
        foreach($item->floor_layout->units as $unit) {
            foreach ($unit->room_layout as $value) {
                $_unit = array_push($unit_arr, $value);
            }
        }
    
    	return response()->json([
    		'floor' => $item->floor_layout,
            'units'  => $item->floor_layout->units,
            'unit' => $unit_arr,
            'types'  => RoomType::all()
    	]);
    }

    /**
     * Filter unit/floor type
     * 
     * @return \Illuminate\Http\Response
     */
    public function filterByType($floor, $type) 
    {

        /** Get units within specific unit type */
        if($type != 'null') {
            $units = Unit::where(['room_type_id' => $type, 'floor_layout_id' => $floor])->get();            
        } else {
            $units = Unit::where(['floor_layout_id' => $floor])->get();            
        }


        return response()->json([
            'units' => $units
        ]);

    }
}

app/Http/Controllers/FloorLayoutController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\FloorLayoutStorePost;

use App\Project;
use App\FloorLayout;


class FloorLayoutController extends Controller
{
    public static $guardResource = 'floor-layout';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Project $project, $name)
    {

        $floors = FloorLayout::where('project_id', $project->id)->get();

        return view('pages.admin.projects.floor-layout.index', [
            'project' => $project,
            'floors' => $floors,
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Project $project, $name)
    {

        $types = FloorLayout::getTypes();

        return view('pages.admin.projects.floor-layout.create', [
            'project' => $project,
            'types' => $types,
            'floors' => $project->building_layouts
        ]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FloorLayoutStorePost $request, Project $project)
    {
        $vars = $request->except([]);
        $vars['project_id'] = $project->id;

        if(FloorLayout::hasFloorLayout($project->id, $request->type)) {
            $vars['status'] = 0;
        } else {
            $vars['status'] = 1;
        }

        if($request->hasFile('image_path')) {
            $vars['image_path'] = $request->file('image_path')->store('floor-layouts', 'public');
        }

        /** Start transaction */
        \DB::beginTransaction();

            /** Store Floor Layout */
            $floor = FloorLayout::create($vars);

        /** End Transaction */
        \DB::commit();


        /** Flash message */
        \PRXAdmin::view()->flash($floor->name .' has been successfully created!', 'Success!', 'success');        

        /** Return to project index */
        return redirect()->route('admin.floor-layout.index', [$project->id, $project->name]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($project, FloorLayout $floor)
    {
        $types = FloorLayout::getTypes();
        $project = Project::find($project);

        return view('pages.admin.projects.floor-layout.edit', [
            'floor' => $floor,
            'types' => $types,
            'layouts' => $project->building_layouts
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FloorLayoutStorePost $request, $project, FloorLayout $floor)
    {   
        $vars = $request->except(['image_path', 'status']);

        if(FloorLayout::hasFloorLayout($project, $request->type, $floor->id)) {
            $vars['status'] = 0;
        } else {
            $vars['status'] = 1;
        }

        if($request->hasFile('image_path')) {

            /** Remove Image from Storage */
            if($floor->image_path) {
                \Storage::delete('public/'. $floor->image_path);
            }

            $vars['image_path'] = $request->file('image_path')->store('floor-layouts', 'public');

        }

        /** Start Transaction */
        \DB::beginTransaction();

            if($request->status) {
                /** Set floor layout to Active */
                FloorLayout::deactivateActiveStatus($floor->type, $floor->project_id, $floor->id);
                $vars['status'] = 1;
            }

            $floor->update($vars);

        /** End Transaction */
        \DB::commit();


        /** Flash message */
        \PRXAdmin::view()->flash($floor->name .' has been successfully updated!', 'Success!', 'success');        

        return back();

    }   

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $floor = FloorLayout::find($id);

        /** Begin Transaction */
        \DB::beginTransaction();

            /** Remove from storage */
            \Storage::delete('public/'. $floor->image_path);

            /** Soft Delete floor */
            $floor->delete();        

        /** End Transaction */
        \DB::commit();

        /** Flash message */
        \PRXAdmin::view()->flash('A floor layout has been successfully archived!', 'Success!', 'success');                

        return back();        

    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ProjectStorePost;

use App\Project;
use Image;

class ProjectController extends Controller
{
    public static $guardResource = 'project';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $projects = Project::get();

        return view('pages.admin.projects.index', [
            'projects' => $projects
        ]);

    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project, $name)
    {
        return view('pages.admin.projects.show', [
            'project' => $project
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project, $name)
    {
        return view('pages.admin.projects.edit', [
            'project' => $project
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectStorePost $request, Project $project)
    {

        $vars = $request->except(['image_path', 'front_outside_image', 'back_outside_image']);

        /** Begin transaction */
        \DB::beginTransaction();

            if($request->hasFile('image_path')) {
                $vars['image_path'] = $request->file('image_path')->store('projects', 'public');
            }

            if($request->hasFile('front_outside_image')) {
                $vars['front_outside_image'] = $request->file('front_outside_image')->store('outside-view', 'public');
            }

            if($request->hasFile('back_outside_image')) {
                $vars['back_outside_image'] = $request->file('back_outside_image')->store('outside-view', 'public');
            }

            /** Update Project */
            $project->update($vars);


        /** Commit transaction */
        \DB::commit();

        /** Flash message */
        \PRXAdmin::view()->flash($project->name. ' has been successfully updated!', 'Success!', 'success');

        return back();

    }
}

resources/views/pages/admin/projects/floor-layout/create.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Floor Layout
        <small>Add Floor Layout</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-image"></i> Add Floor Layout</a></li>
        <li class="active">Create</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-header">
                    <h3 class="box-title">Add Floor Layout for {{ $project->name }}</h3>
                </div>
                <div class="box-body">
                    
                    @include('PRXAdmin::includes.form-errors')

                    <!-- form start -->
                    <form role="form" method="post" action="{{ route('admin.floor-layout.store', $project->id) }}" 
                        enctype="multipart/form-data">

                        {{ csrf_field() }}

                        <div class="box-body">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input type="text" name="name" id="name" class="form-control" required>
                                    </div> 
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Type</label>
                                        <select class="form-control" id="type" name="type">
                                            @foreach($types as $type)

                                                <option value="{{ $type['value'] }}">{{ $type['name'] }}</option>

                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Floor</label>
                                        <select class="form-control" id="building_layout_id" name="building_layout_id">
                                            @foreach($floors as $floor)

                                                <option value="{{ $floor->id }}">{{ $floor->floor }}</option>

                                            @endforeach
                                        </select>
                                    </div>
                                </div>


                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Description</label>
                                        <textarea id="description" name="description" rows="3" class="form-control">{{ old('description') }}</textarea>
                                    </div> 
                                </div>


                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Image</label>
                                        <input type="file" name="image_path" id="image_path" class="form-control" required>
                                    </div> 
                                </div>

                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer text-right">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop

resources/views/pages/admin/projects/floor-layout/edit.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Floor Layout
        <small>Update Floor Layout</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-edit"></i> Update {{ $floor->name }}</a></li>
        <li class="active">Create</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-header">
                    <h3 class="box-title">Update {{ $floor->name }}</h3>
                </div>
                <div class="box-body">
                    
                    @include('PRXAdmin::includes.form-errors')

                    <!-- form start -->
                    <form role="form" method="post" action="{{ route('admin.floor-layout.update', [$floor->project_id, $floor->id]) }}" 
                        enctype="multipart/form-data">

                        {{ csrf_field() }}
                        {{ method_field('PUT') }}

                        <div class="box-body">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input type="text" name="name" id="name" class="form-control" required value="{{ $floor->name }}">
                                    </div> 
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Type</label>
                                        <select class="form-control" id="type" name="type">
                                            @foreach($types as $type)

                                                <option value="{{ $type['value'] }}" 
                                                    @if($floor->type === $type['value'])
                                                        selected 
                                                    @endif
                                                >
                                                {{ $type['name'] }}</option>

                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Floor</label>
                                        <select class="form-control" id="building_layout_id" name="building_layout_id">
                                            @foreach($layouts as $layout)

                                                <option value="{{ $layout->id }}"
                                                    @if($floor->building_layout_id === $layout->id)
                                                        selected 
                                                    @endif
                                                >{{ $layout->floor }}</option>

                                            @endforeach
                                        </select>
                                    </div>
                                </div>


                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Description</label>
                                        <textarea id="description" name="description" rows="3" class="form-control">{{ $floor->description }}</textarea>
                                    </div> 
                                </div>

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <img class="img-responsive" src="{{ $floor->renderImagePath() }}">
                                    </div>
                                </div>

                                <div class="col-md-12">

                                    <div class="form-group">
                                        <label>Image</label>
                                        <input type="file" name="image_path" id="image_path" class="form-control">
                                    </div> 
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <br />
                                        <input name="status" type="checkbox" class="form-control bootstrap-toggle" data-toggle="toggle" data-on="Active" data-off="In Active" data-width="100" data-height="35" {{ $floor->status ? 'checked' : '' }}>
                                    </div>                                
                                </div>  

                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer text-right">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop

resources/views/pages/admin/projects/floor-layout/index.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Floor Layout
        <small>Floor Layout of {{ $project->name }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-image"></i> Floor Layout of {{ $project->name }}</a></li>
        <li class="active">Index</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row margin-bottom">
        <div class="col-md-12">
         
            <a href="{{ route('admin.floor-layout.create', [$project->id, $project->name]) }}" type="button" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Add Floor Layout</a>

        </div>

        <!-- /.col -->
    </div>
    <!-- /.row -->      

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Floor Layout</h3>
                </div>
                <div class="box-body">

                    <!-- Unit -->                    
                    <div class="col-xs-12">
                        <table id="roomTable" class="dataTables table table-bordered">
                            <thead>
                                <th>Project</th>
                                <th>Type</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Image</th>
                                <th>Status</th>
                                <th>Action</th>
                            </thead>

                            <tbody>
                                @foreach($floors as $floor)
                                    <tr>
                                        <td>{{ $floor->project->name }}</td>
                                        <td>{{ $floor->findType() }}</td>
                                        <td>{{ $floor->name }}</td>
                                        <td>{{ $floor->renderShortDescription() }}</td>
                                        <td>
                                            <img src="{{ $floor->renderImagePath() }}" width="50" height="50" alt="{{ $floor->name }}">
                                        </td>
                                        <td>{!! $floor->renderStatus() !!}</td>
                                        <td>
                                            <a href="{{ route('admin.floor-layout.edit', [$floor->project_id, $floor->id]) }}" class="btn btn-sm btn-primary">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a class="btn btn-sm btn-danger deleteBtn"
                                                data-action="{{ route('admin.floor-layout.destroy', $floor->id) }}"
                                                data-message="Are you sure you want to archived {{ $floor->name }} ?">
                                                <i class="fa fa-trash"></i>
                                            </a>

                                            <a href="{{route('admin.units.index', [$floor->id, $floor->name]) }}" class="btn btn-sm btn-success"><i class="fa fa-building"></i> Manage Units</a>

                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div> <!-- Unit ./end -->                

                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop