routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin/login');
});

Route::get('/home', function () {
    return redirect('/admin/login');
});


/*
|--------------------------------------------------------------------------
| @PRX Admin Routes
|--------------------------------------------------------------------------
*/
Route::name('admin.')
    ->prefix('admin')
    ->middleware('prxadmin')
    ->group(function() { 


		/*
		|--------------------------------------------------------------------------
		| @Room
		|--------------------------------------------------------------------------
		*/
		Route::resource('rooms', 'RoomController')->except([
			'create',
			'show'
		]);
		Route::get('rooms/create/{project?}/{name?}', 'RoomController@create')->name('rooms.create');

		/*
		|--------------------------------------------------------------------------
		| @Amenities
		|--------------------------------------------------------------------------
		*/
		Route::resource('amenities', 'AmenityController')->except([
			'create',
			'show'
		]);
		Route::get('amenities/create/{project?}/{name?}', 'AmenityController@create')->name('amenities.create');	


		/*
		|--------------------------------------------------------------------------
		| @Commercial Areas
		|--------------------------------------------------------------------------
		*/
		Route::resource('commercial-areas', 'CommercialAreaController')->except([
			'create',
			'show'
		]);
		Route::get('commercial-areas/create/{project?}/{name?}', 'CommercialAreaController@create')->name('commercial-areas.create');	


		/*
		|--------------------------------------------------------------------------
		| @Sold Out Project
		|--------------------------------------------------------------------------
		*/
		Route::resource('sold-out-projects', 'SoldOutProjectController')->except([
			'show'
		]);
		Route::get('sold-out-projects/{project}/{name}', 'SoldOutProjectController@show')->name('sold-out-projects.show');		

		/*
		|--------------------------------------------------------------------------
		| @Room Layout
		|--------------------------------------------------------------------------
		*/
		// Route::resource('room-layout', 'RoomLayoutController')->except([
		// 	'create',
		// 	'show'
		// ]);
		// Route::get('room-layout/create/{floor_layout?}/{name?}', 'RoomLayoutController@create')->name('room-layout.create');

		/*
		|--------------------------------------------------------------------------
		| @Home page banner
		|--------------------------------------------------------------------------
		*/
		Route::resource('home-banner', 'HomeBannerController')->except([
			'show',
			'destroy'
		]);

		/*
		|--------------------------------------------------------------------------
		| @General Page
		|--------------------------------------------------------------------------
		*/
		Route::resource('general-pages', 'GeneralPageController')->except([
			'create',
			'store',
			'show',
			'destroy'
		]);
		Route::get('general-pages/{page}/{name}', 'GeneralPageController@show')->name('general-pages.show');

		/*
		|--------------------------------------------------------------------------
		| @General Page item
		|--------------------------------------------------------------------------
		*/
		Route::resource('general-page-item', 'GeneralPageItemController')->except([
			'create',
			'store',
			'show',
			'destroy'
		]);

		Route::resource('exchange_rates', 'ExchangeRateController');

		Route::resource('room_types', 'RoomTypeController');


		Route::group(['prefix' => 'projects'], function() {

			/*
			|--------------------------------------------------------------------------
			| @Project
			|--------------------------------------------------------------------------
			*/
			Route::get('/', 'ProjectController@index')->name('project.index');
			Route::get('{project}/{name}', 'ProjectController@show')->name('project.view');
			Route::get('edit/{project}/{name}', 'ProjectController@edit')->name('project.edit');
			Route::put('update/{project}', 'ProjectController@update')->name('project.update');

			Route::get('building-layout/{project}/{name}', 'BuildingLayoutController@index')->name('building-layouts.index');
			Route::get('/building-layout/store/{project}/{name}', 'BuildingLayoutController@create')->name('project.layout.create');
			Route::post('/building-layouts/store/{project}', 'BuildingLayoutController@store')->name('building-layout.store');
			Route::get('building-layout/{project}/{layout}/edit', 'BuildingLayoutController@edit')->name('building-layout.edit');
			Route::put('building-layout/{layout}/update', 'BuildingLayoutController@update')->name('building-layout.update');	
			Route::delete('building-layout/{layout}/destroy', 'BuildingLayoutController@destroy')->name('building-layout.destroy');		



			/*
			|--------------------------------------------------------------------------
			| @Gallery
			|--------------------------------------------------------------------------
			*/	
			Route::get('gallery/{project}/{name}', 'GalleryController@index')->name('gallery.index');
			Route::get('gallery/create/{project}/{name}', 'GalleryController@create')->name('gallery.create');
			Route::get('gallery/edit/{id}/{project}/{name}', 'GalleryController@edit')->name('gallery.edit');
			Route::post('gallery/store/{project}', 'GalleryController@store')->name('gallery.store');
			Route::put('gallery/update/{id}', 'GalleryController@update')->name('gallery.update');
			Route::delete('gallery/destroy/{id}', 'GalleryController@destroy')->name('gallery.destroy');

			/*
			|--------------------------------------------------------------------------
			| @Floor Layout
			|--------------------------------------------------------------------------
			*/
			Route::get('{project}/{name}/floor-layouts/', 'FloorLayoutController@index')->name('floor-layout.index');
			Route::get('{project}/{name}/floor-layoust/create', 'FloorLayoutController@create')->name('floor-layout.create');
			Route::post('{project}/floor-layouts/store', 'FloorLayoutController@store')->name('floor-layout.store');
			Route::get('/{project?}/{floor}/floor-layouts/edit', 'FloorLayoutController@edit')->name('floor-layout.edit');

			Route::put('{project?}/{floor}/floor-layouts/update', 'FloorLayoutController@update')->name('floor-layout.update');

			Route::delete('floor-layouts/{floor}/destroy', 'FloorLayoutController@destroy')->name('floor-layout.destroy');


			/*
			|--------------------------------------------------------------------------
			| @Floor Layout
			|--------------------------------------------------------------------------
			*/
			Route::get('units/{floor}/{name}', 'UnitController@index')->name('units.index');
			Route::get('units/{floor}/{name}/create', 'UnitController@create')->name('units.create');
			Route::post('units/{floor}/store', 'UnitController@store')->name('units.store');
			Route::get('units/{floor}/{unit}/edit', 'UnitController@edit')->name('units.edit');
			Route::put('units/{unit}/update', 'UnitController@update')->name('units.update');	
			Route::delete('units/{unit}/destroy', 'UnitController@destroy')->name('units.destroy');	

			/*
			|--------------------------------------------------------------------------
			| @Room Layout
			|--------------------------------------------------------------------------
			*/
			// Route::get('room-layouts/{floor}/{name}', 'RoomLayoutController@index')->name('room-layouts.index');	
			// Route::get('room-layouts/{floor}/{name}/create', 'RoomLayoutController@create')->name('room-layouts.create');	
			// Route::post('room-layouts/store', 'RoomLayoutController@store')->name('room-layouts.store');	
			// Route::get('room-layouts/{id}/{unit}/edit', 'RoomLayoutController@edit')->name('room-layouts.edit');	
			// Route::put('room-layouts/{roomlayout}/update', 'RoomLayoutController@update')->name('room-layouts.update');
			// Route::delete('room-layouts/{roomlayout}/destroy', 'RoomLayoutController@destroy')->name('room-layouts.destroy');			
		});

});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Amenity;
use App\CommercialArea;
use App\Room;
use App\Gallery;

class Project extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = [
		'name', 'description', 'address',
        'image_path','longitude', 'latitude', 
        'footer', 'front_outside_image', 'back_outside_image',
        'landmark'
	];

    /*
    |-----------------------------------------------
    | @Relationships
    |-----------------------------------------------
    */

    public function rooms() 
    {
    	return $this->hasMany(Room::class);
    }

    public function amenities() 
    {
        return $this->hasMany(Amenity::class);
    }
    
    public function commercial_areas() 
    {
        return $this->hasMany(CommercialArea::class);
    }

    public function gallery_images() 
    {
        return $this->hasMany(Gallery::class);
    }

    public function building_layouts()
    {
        return $this->hasMany(BuildingLayout::class);
    }

    public function renderImagePath()
    {
        if($this->image_path) {
            return '/storage/' . $this->image_path;
        }
    }

    public function renderOutsideFrontView()
    {
        if($this->front_outside_image) {
            return '/storage/' . $this->front_outside_image;
        }
    }

    public function renderOutsideBackView()
    {
        if($this->back_outside_image) {
            return '/storage/' . $this->back_outside_image;
        }
    }

}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ProjectStorePost;

use App\Project;
use Image;

class ProjectController extends Controller
{
    public static $guardResource = 'project';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $projects = Project::get();

        return view('pages.admin.projects.index', [
            'projects' => $projects
        ]);

    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project, $name)
    {
        return view('pages.admin.projects.show', [
            'project' => $project
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project, $name)
    {
        return view('pages.admin.projects.edit', [
            'project' => $project
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectStorePost $request, Project $project)
    {

        $vars = $request->except(['image_path', 'front_outside_image', 'back_outside_image']);

        /** Begin transaction */
        \DB::beginTransaction();

            if($request->hasFile('image_path')) {
                $vars['image_path'] = $request->file('image_path')->store('projects', 'public');
            }

            if($request->hasFile('front_outside_image')) {
                $vars['front_outside_image'] = $request->file('front_outside_image')->store('outside-view', 'public');
            }

            if($request->hasFile('back_outside_image')) {
                $vars['back_outside_image'] = $request->file('back_outside_image')->store('outside-view', 'public');
            }

            /** Update Project */
            $project->update($vars);


        /** Commit transaction */
        \DB::commit();

        /** Flash message */
        \PRXAdmin::view()->flash($project->name. ' has been successfully updated!', 'Success!', 'success');

        return back();

    }
}

resources/views/pages/admin/projects/edit.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {{ $project->name }}
        <small>Update {{ $project->name }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-building"></i> {{ $project->name }}</a></li>
        <li class="active">Update</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-header">
                    <h3 class="box-title">Update {{ $project->name }}</h3>
                </div>
                <div class="box-body">
                    
                    @include('PRXAdmin::includes.form-errors')

                    <form role="form" method="post" action="{{ route('admin.project.update', $project->id) }}" enctype="multipart/form-data">
                        
                        {{ csrf_field() }}

                        {{ method_field('PUT') }}

                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input name="name" type="name" class="form-control" placeholder="Name" required value="{{ $project->name }}">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea id="description" name="description" placeholder="Description" class="form-control" rows="5">{{ $project->description }}</textarea>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="address">Address</label>
                                        <input type="text" id="address" name="address" class="form-control" required value="{{ $project->address }}">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="landmark">Landmark</label>
                                        <input type="text" id="landmark" name="landmark" class="form-control" required value="{{ $project->landmark }}">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="latitude">Latitude</label>
                                        <input type="text" id="latitude" name="latitude" class="form-control" required value="{{ $project->latitude }}">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="longitude">Longitude</label>
                                        <input type="text" id="longitude" name="longitude" class="form-control" required value="{{ $project->longitude }}">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="footer">Footer <small>(Description)</small></label>
                                        <textarea id="footer" name="footer" placeholder="Footer (Description)" class="form-control" rows="5">{{ $project->footer }}</textarea>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="form-group"> 
                                            <label for="image_path">Building Image <i>(Should be a landscape image)</i></label> 
                                            <a @if($project->image_path) href="{{ $project->renderImagePath() }}" @endif target="_blank" class="btn @if($project->image_path) btn-info @else btn-danger @endif btn-sm">@if($project->image_path) View Building Image @else No Building image @endif</a></a>
                                        </div>
                                        <input type="file" id="image_path" name="image_path" class="form-control" required>
                                    </div>
                                </div>
                                
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label>Outside View <small>(Front view)</small></label>
                                            <a @if($project->front_outside_image) href="{{ $project->renderOutsideFrontView() }}" @endif target="_blank" class="btn @if($project->front_outside_image) btn-info @else btn-danger @endif btn-sm">@if($project->front_outside_image) View Outside Image @else No Outside image (Front view) @endif</a>
                                        </div>
                                        <input type="file" name="front_outside_image" id="front_outside_image" class="form-control" required>
                                    </div> 
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label>Outside View <small>(Back view)</small></label>
                                            <a @if($project->back_outside_image) href="{{ $project->renderOutsideBackView() }}" @endif target="_blank" class="btn @if($project->back_outside_image) btn-info @else btn-danger @endif btn-sm">@if($project->back_outside_image) View Outside Image @else No Outside image (Back view) @endif</a>
                                        </div>
                                        <input type="file" name="back_outside_image" id="back_outside_image" class="form-control" required>
                                    </div> 
                                </div>
                            </div>
                        </div>

                        <!-- /.box-body -->

                        <div class="box-footer text-right">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop

@section('js')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript">
        function renderImage(input){
            if(input.files && input.files[0]){
                var reader = new FileReader();

                reader.onload = function(e){
                    $('#image_file').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#image_path').change(function(){
            $('#image_file').show();
            if($('#image_path').val() === ''){
                $('#image_file').hide();
            }
            renderImage(this);
        });
    </script>
@endsection

resources/views/pages/admin/projects/index.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Projects
        <small>List of Projects</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-building"></i> Projects</a></li>
        <li class="active">Index</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row margin-bottom">
        <div class="col-md-12">
         
        </div>

        <!-- /.col -->
    </div>
    <!-- /.row -->      

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Projects</h3>
                </div>
                <div class="box-body">
                    
                    @foreach($projects as $project)

                        <div class="col-xs-4">
                            <a type="button" href="{{ route('admin.project.view', [$project->id, $project->name]) }}" class="btn btn-large btn-lg btn-block btn-primary"><i class="fa fa-building"></i> {{ $project->name }}</a>
                        </div>

                    @endforeach

                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop

resources/views/pages/admin/projects/show.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {{ $project->name }}
        <small>Show {{ $project->name }}</small>
        
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-building"></i> {{ $project->name }}</a></li>
        <li class="active">Show</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row margin-bottom">
        <div class="col-md-12">
                
            <a href="{{ route('admin.project.edit', [$project->id, $project->name]) }}" type="button" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</a>

            <a href="{{ route('admin.gallery.index', [$project->id, $project->name]) }}" type="button" class="btn btn-info"><i class="fa fa-image"></i> View Gallery</a>

            <a href="{{ route('admin.building-layouts.index', [$project->id, $project->name]) }}" type="button" class="btn btn-danger"><i class="fas fa-eye"></i> View Building Layout</a>

            <a href="{{ route('admin.floor-layout.index', [$project->id, $project->name]) }}" type="button" class="btn btn-success"><i class="fas fa-eye"></i> View Floor Layout</a>

        </div>

        <!-- /.col -->
    </div>
    <!-- /.row -->      

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">{{ $project->name }}</h3>
                </div>
                <div class="box-body">
                    
                    <!-- Room -->                    
                    <div class="col-xs-12">
                        <div class="form-group">
                            <h3>Rooms List</h3>

                            <a href="{{ route('admin.rooms.create', [$project->id, $project->name]) }}" type="button" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add Room</a>
                        </div>

                        <table id="roomTable" class="dataTables table table-bordered">
                            <thead>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Image</th>
                                <th>Action</th>
                            </thead>

                            <tbody>
                                @foreach($project->rooms as $room)
                                    <tr>
                                        <td>{{ $room->name }}</td>
                                        <td>{{ $room->renderShortDescription() }}</td>
                                        <td>
                                            <img src="{{ $room->renderImagePath() }}" width="50" height="50" alt="{{ $room->name }}">
                                        </td>
                                        <td>
                                            <a href="{{ route('admin.rooms.edit', [$room->id]) }}" class="btn btn-sm btn-primary">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a class="btn btn-sm btn-danger deleteBtn"
                                                data-action="{{ route('admin.rooms.destroy', $room->id) }}"
                                                data-message="Are you sure you want to archived {{ $room->name }} ?">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div> <!-- Rooms ./end -->


                    <!--  Amenities -->
                    <div class="col-xs-12">
                        <div class="form-group">
                            <h3>Amenities List</h3>

                            <a href="{{ route('admin.amenities.create', [$project->id, $project->name]) }}" type="button" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add Amenities</a>
                        </div>

                        <table id="amenitiesTable" class="dataTables table table-bordered">
                            <thead>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Image</th>
                                <th>Action</th>
                            </thead>

                            <tbody>
                                @foreach($project->amenities as $amenity)
                                    <tr>
                                        <td>{{ $amenity->name }}</td>
                                        <td>{{ $amenity->renderShortDescription() }}</td>
                                        <td>
                                            <img src="{{ $amenity->renderImagePath() }}" width="50" height="50" alt="{{ $amenity->name }}">
                                        </td>
                                        <td>
                                            <a href="{{ route('admin.amenities.edit', [$amenity->id]) }}" class="btn btn-sm btn-primary">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a class="btn btn-sm btn-danger deleteBtn"
                                                data-action="{{ route('admin.amenities.destroy', $amenity->id) }}"
                                                data-message="Are you sure you want to archived {{ $amenity->name }} ?">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>

                    <!-- Commercial Areas -->
                    <div class="col-xs-12">
                        <div class="form-group">
                            <h3>Commercial Areas List</h3>

                            <a href="{{ route('admin.commercial-areas.create', [$project->id, $project->name]) }}" type="button" class="btn btn-success"><i class="fa fa-plus-circle"></i> Add Amenities</a>
                        </div>

                        <table id="commercialAreaTable" class="dataTables table table-bordered">
                            <thead>
                                <th>Name</th>
                                {{-- <th>Description</th> --}}
                                <th>Image</th>
                                <th>Action</th>
                            </thead>

                            <tbody>
                                @foreach($project->commercial_areas as $commercial_area)
                                    <tr>
                                        <td>{{ $commercial_area->name }}</td>
                                        {{-- <td>{{ $commercial_area->renderShortDescription() }}</td> --}}
                                        <td>
                                            <img src="{{ $commercial_area->renderImagePath() }}" width="50" height="50" alt="{{ $commercial_area->name }}">
                                        </td>
                                        <td>
                                            <a href="{{ route('admin.commercial-areas.edit', [$commercial_area->id]) }}" class="btn btn-sm btn-primary">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                            <a class="btn btn-sm btn-danger deleteBtn"
                                                data-action="{{ route('admin.commercial-areas.destroy', $commercial_area->id) }}"
                                                data-message="Are you sure you want to archived {{ $commercial_area->name }} ?">
                                                <i class="fa fa-trash"></i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>


                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop