routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin/login');
});

Route::get('/home', function () {
    return redirect('/admin/login');
});


/*
|--------------------------------------------------------------------------
| @PRX Admin Routes
|--------------------------------------------------------------------------
*/
Route::name('admin.')
    ->prefix('admin')
    ->middleware('prxadmin')
    ->group(function() { 


		/*
		|--------------------------------------------------------------------------
		| @Room
		|--------------------------------------------------------------------------
		*/
		Route::resource('rooms', 'RoomController')->except([
			'create',
			'show'
		]);
		Route::get('rooms/create/{project?}/{name?}', 'RoomController@create')->name('rooms.create');

		/*
		|--------------------------------------------------------------------------
		| @Amenities
		|--------------------------------------------------------------------------
		*/
		Route::resource('amenities', 'AmenityController')->except([
			'create',
			'show'
		]);
		Route::get('amenities/create/{project?}/{name?}', 'AmenityController@create')->name('amenities.create');	


		/*
		|--------------------------------------------------------------------------
		| @Commercial Areas
		|--------------------------------------------------------------------------
		*/
		Route::resource('commercial-areas', 'CommercialAreaController')->except([
			'create',
			'show'
		]);
		Route::get('commercial-areas/create/{project?}/{name?}', 'CommercialAreaController@create')->name('commercial-areas.create');	


		/*
		|--------------------------------------------------------------------------
		| @Sold Out Project
		|--------------------------------------------------------------------------
		*/
		Route::resource('sold-out-projects', 'SoldOutProjectController')->except([
			'show'
		]);
		Route::get('sold-out-projects/{project}/{name}', 'SoldOutProjectController@show')->name('sold-out-projects.show');		

		/*
		|--------------------------------------------------------------------------
		| @Room Layout
		|--------------------------------------------------------------------------
		*/
		// Route::resource('room-layout', 'RoomLayoutController')->except([
		// 	'create',
		// 	'show'
		// ]);
		// Route::get('room-layout/create/{floor_layout?}/{name?}', 'RoomLayoutController@create')->name('room-layout.create');

		/*
		|--------------------------------------------------------------------------
		| @Home page banner
		|--------------------------------------------------------------------------
		*/
		Route::resource('home-banner', 'HomeBannerController')->except([
			'show',
			'destroy'
		]);

		/*
		|--------------------------------------------------------------------------
		| @General Page
		|--------------------------------------------------------------------------
		*/
		Route::resource('general-pages', 'GeneralPageController')->except([
			'create',
			'store',
			'show',
			'destroy'
		]);
		Route::get('general-pages/{page}/{name}', 'GeneralPageController@show')->name('general-pages.show');

		/*
		|--------------------------------------------------------------------------
		| @General Page item
		|--------------------------------------------------------------------------
		*/
		Route::resource('general-page-item', 'GeneralPageItemController')->except([
			'create',
			'store',
			'show',
			'destroy'
		]);

		Route::resource('exchange_rates', 'ExchangeRateController');

		Route::resource('room_types', 'RoomTypeController');


		Route::group(['prefix' => 'projects'], function() {

			/*
			|--------------------------------------------------------------------------
			| @Project
			|--------------------------------------------------------------------------
			*/
			Route::get('/', 'ProjectController@index')->name('project.index');
			Route::get('{project}/{name}', 'ProjectController@show')->name('project.view');
			Route::get('edit/{project}/{name}', 'ProjectController@edit')->name('project.edit');
			Route::put('update/{project}', 'ProjectController@update')->name('project.update');

			Route::get('building-layout/{project}/{name}', 'BuildingLayoutController@index')->name('building-layouts.index');
			Route::get('/building-layout/store/{project}/{name}', 'BuildingLayoutController@create')->name('project.layout.create');
			Route::post('/building-layouts/store/{project}', 'BuildingLayoutController@store')->name('building-layout.store');
			Route::get('building-layout/{project}/{layout}/edit', 'BuildingLayoutController@edit')->name('building-layout.edit');
			Route::put('building-layout/{layout}/update', 'BuildingLayoutController@update')->name('building-layout.update');	
			Route::delete('building-layout/{layout}/destroy', 'BuildingLayoutController@destroy')->name('building-layout.destroy');		



			/*
			|--------------------------------------------------------------------------
			| @Gallery
			|--------------------------------------------------------------------------
			*/	
			Route::get('gallery/{project}/{name}', 'GalleryController@index')->name('gallery.index');
			Route::get('gallery/create/{project}/{name}', 'GalleryController@create')->name('gallery.create');
			Route::get('gallery/edit/{id}/{project}/{name}', 'GalleryController@edit')->name('gallery.edit');
			Route::post('gallery/store/{project}', 'GalleryController@store')->name('gallery.store');
			Route::put('gallery/update/{id}', 'GalleryController@update')->name('gallery.update');
			Route::delete('gallery/destroy/{id}', 'GalleryController@destroy')->name('gallery.destroy');

			/*
			|--------------------------------------------------------------------------
			| @Floor Layout
			|--------------------------------------------------------------------------
			*/
			Route::get('{project}/{name}/floor-layouts/', 'FloorLayoutController@index')->name('floor-layout.index');
			Route::get('{project}/{name}/floor-layoust/create', 'FloorLayoutController@create')->name('floor-layout.create');
			Route::post('{project}/floor-layouts/store', 'FloorLayoutController@store')->name('floor-layout.store');
			Route::get('/{project?}/{floor}/floor-layouts/edit', 'FloorLayoutController@edit')->name('floor-layout.edit');

			Route::put('{project?}/{floor}/floor-layouts/update', 'FloorLayoutController@update')->name('floor-layout.update');

			Route::delete('floor-layouts/{floor}/destroy', 'FloorLayoutController@destroy')->name('floor-layout.destroy');


			/*
			|--------------------------------------------------------------------------
			| @Floor Layout
			|--------------------------------------------------------------------------
			*/
			Route::get('units/{floor}/{name}', 'UnitController@index')->name('units.index');
			Route::get('units/{floor}/{name}/create', 'UnitController@create')->name('units.create');
			Route::post('units/{floor}/store', 'UnitController@store')->name('units.store');
			Route::get('units/{floor}/{unit}/edit', 'UnitController@edit')->name('units.edit');
			Route::put('units/{unit}/update', 'UnitController@update')->name('units.update');	
			Route::delete('units/{unit}/destroy', 'UnitController@destroy')->name('units.destroy');	

			/*
			|--------------------------------------------------------------------------
			| @Room Layout
			|--------------------------------------------------------------------------
			*/
			// Route::get('room-layouts/{floor}/{name}', 'RoomLayoutController@index')->name('room-layouts.index');	
			// Route::get('room-layouts/{floor}/{name}/create', 'RoomLayoutController@create')->name('room-layouts.create');	
			// Route::post('room-layouts/store', 'RoomLayoutController@store')->name('room-layouts.store');	
			// Route::get('room-layouts/{id}/{unit}/edit', 'RoomLayoutController@edit')->name('room-layouts.edit');	
			// Route::put('room-layouts/{roomlayout}/update', 'RoomLayoutController@update')->name('room-layouts.update');
			// Route::delete('room-layouts/{roomlayout}/destroy', 'RoomLayoutController@destroy')->name('room-layouts.destroy');			
		});

});

app/SoldOutProject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SoldOutProject extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $fillable = [
		'name', 'description', 'image_path'
	];


	/*
    |-----------------------------------------------
    | @Render
    |-----------------------------------------------
    */

    /**
     * Rendering Image Path
     * 
     * @return string
     */
    public function renderImagePath()
    {

    	if($this->image_path) {
    		return '/storage/'. $this->image_path;

    	}

    }

}

app/Http/Controllers/SoldOutProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\SoldOutProjectStorePost;

use App\SoldOutProject;

class SoldOutProjectController extends Controller
{
    public static $guardResource = 'sold-out-projects';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $soldOutProjects = SoldOutProject::get();

        return view('pages.admin.sold-out-projects.index', [
            'soldOutProjects' => $soldOutProjects
        ]);      
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.sold-out-projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SoldOutProjectStorePost $request)
    {
        $vars = $request->except(['image_path']);

        if($request->hasFile('image_path')) {
            $vars['image_path'] = $request->file('image_path')->store('sold-out-projects-image', 'public');
        }

        /** Begins transaction */
        \DB::beginTransaction();

            /** Create Sold out project */
            $soldOutProject =  SoldOutProject::create($vars);

        /** End transaction */
        \DB::commit();

        /** Flash message */
        \PRXAdmin::view()->flash($soldOutProject->name .' has been successfully created!', 'Success!', 'success');        

        /** Return to sold out project index */
        return redirect()->route('admin.sold-out-projects.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(SoldOutProject $project, $name)
    {
        return view('pages.admin.sold-out-projects.show', [
            'project' => $project
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $project = SoldOutProject::find($id);

        return view('pages.admin.sold-out-projects.edit', [
            'project' => $project
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SoldOutProjectStorePost $request, $id)
    {
        /** Find Soldoutproject */
        $project = SoldOutProject::find($id);
        $vars = $request->except(['image_path']);

        if($request->hasFile('image_path')) {

            if($project->image_path) {

                /** Delete file/image in storage */
                \Storage::delete('public/'. $project->image_path);                
            }
           
            $vars['image_path'] = $request->file('image_path')->store('sold-out-projects-image', 'public');
        }

        /** Begin transaction */
        \DB::beginTransaction();

            /** Update sold out project */
            $project->update($vars);

        /** Commit transaction */
        \DB::commit();


        /** Flash message */
        \PRXAdmin::view()->flash($project->name .' has been successfully updated!', 'Success!', 'success');                

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $project = SoldOutProject::find($id);

        /** Begin transaction */
        \DB::beginTransaction();

            /** Remove from storage */
            \Storage::delete('public/'. $project->image_path);

            /** Soft delete sold out project */
            $project->delete();

        /** End transaction */
        \DB::commit();

        /** Flash message */
        \PRXAdmin::view()->flash('Project has been successfully archived!', 'Success!', 'success');        

        return redirect()->route('admin.sold-out-projects.index');
    }
}

resources/views/pages/admin/sold-out-projects/create.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Sold Out Project
        <small>Create Sold Out Project</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-building"></i> Sold Out Project</a></li>
        <li class="active">Create</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-header">
                    <h3 class="box-title">Create Sold Out Project</h3>
                </div>
                <div class="box-body">
                    
                    @include('PRXAdmin::includes.form-errors')

                    <!-- form start -->
                    <form role="form" method="post" action="{{ route('admin.sold-out-projects.store') }}" 
                        enctype="multipart/form-data">

                        {{ csrf_field() }}

                        <div class="box-body">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input type="text" name="name" id="name" class="form-control" placeholder="Name" value="{{ old('name') }}" required>
                                    </div> 
                                </div>

                            {{--     <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Description</label>
                                        <textarea id="description" name="description" rows="3" class="form-control">{{ old('description') }}</textarea>
                                    </div> 
                                </div> --}}


                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Image</label>
                                        <input type="file" name="image_path" id="image_path" class="form-control" required>
                                    </div> 
                                </div>

                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer text-right">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop

resources/views/pages/admin/sold-out-projects/edit.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {{ $project->name }}
        <small>Update {{ $project->name }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-building"></i> {{ $project->name }}</a></li>
        <li class="active">Update</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-default">
                <div class="box-header">
                    <h3 class="box-title">Update {{ $project->name }}</h3>
                </div>
                <div class="box-body">
                    
                    @include('PRXAdmin::includes.form-errors')

                    <form role="form" method="post" action="{{ route('admin.sold-out-projects.update', $project->id) }}"
                        enctype="multipart/form-data">
                        
                        {{ csrf_field() }}

                        {{ method_field('PUT') }}

                        <div class="box-body">
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input name="name" type="name" class="form-control" placeholder="Name" required value="{{ $project->name }}">
                                    </div>
                                </div>

                                {{-- <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea id="description" name="description" placeholder="Description" class="form-control" rows="5">{{ $project->description }}</textarea>
                                    </div>
                                </div> --}}

                                <div class="col-md-12">
                                    <div class="form-group">
                                        
                                        <label for="image_path">Image</label>

                                        <div class="form-group">
                                            <img src="{{ $project->renderImagePath() }}" width="300" height="200">
                                        </div>

                                        <input type="file" name="image_path" id="image_path" class="form-control">
                                    </div>
                                </div>                                


                            </div>
                        </div>

                        <!-- /.box-body -->

                        <div class="box-footer text-right">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>

                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop

resources/views/pages/admin/sold-out-projects/index.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Sold Out Projects
        <small>List of Sold Out Projects</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-building"></i> Sold Out Projects</a></li>
        <li class="active">Index</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row margin-bottom">
        <div class="col-md-12">

            <a href="{{ route('admin.sold-out-projects.create') }}" type="button" class="btn btn-primary"><i class="fa fa-plus-circle"></i> Add Sold Out Project</a>

        </div>

        <!-- /.col -->
    </div>
    <!-- /.row -->      

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Sold Out Projects</h3>
                </div>
                <div class="box-body">
                    

                    @if(!count($soldOutProjects))
                        <div class="form-group text-center">
                            <label>No Sold out Projects. <a href="{{ route('admin.sold-out-projects.create') }}">Add now?</a></label>
                        </div>
                    @endif


                    @foreach($soldOutProjects as $project)

                        <div class="col-xs-4">
                            <div class="form-group">
                                <a type="button" href="{{ route('admin.sold-out-projects.show', [$project->id, $project->name]) }}" class="btn btn-large btn-lg btn-block btn-primary"><i class="fa fa-building"></i> {{ $project->name }}</a>
                            </div>
                        </div>

                    @endforeach


                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop

resources/views/pages/admin/sold-out-projects/show.blade.php
@extends('PRXAdmin::master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {{ $project->name }}
        <small>Show {{ $project->name }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href=""><i class="fa fa-building"></i> {{ $project->name }}</a></li>
        <li class="active">Show</li>
    </ol>

</section>

<!-- Main content -->
<section class="content">

    <div class="row margin-bottom">
        <div class="col-md-12">

            <a href="{{ route('admin.sold-out-projects.edit', $project->id) }}" type="button" class="btn btn-primary"><i class="fa fa-edit"></i> Edit {{ $project->name }}</a>

            <a type="button" class="btn btn-danger deleteBtn"
                data-action="{{ route('admin.sold-out-projects.destroy', $project->id) }}"
                data-message="Are you sure you want to archived {{ $project->name }} ?"
            ><i class="fa fa-trash"></i> Archive {{ $project->name }}</a>

        </div>

        <!-- /.col -->
    </div>
    <!-- /.row -->      

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">{{ $project->name }}</h3>
                </div>
                <div class="box-body">
                    <div class="col-xs-6">
                        
                        <img class="img-responsive"
                        src="{{ $project->renderImagePath() }}">

                    </div>

                    <div class="col-xs-6">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Project Name: <span class="label label-primary">{{ $project->name }}</span></label>
                            </div>
                        </div>

                     {{--    <div class="col-md-12">
                            <div class="form-group">
                                <label>Description: </label>
                                <span>{{ $project->description }}</span>
                            </div>
                        </div> --}}


                    </div>
                </div>
                <!-- /.box-body -->
             </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->    
</section>
<!-- /.content -->
@stop